name: Lint
on:
  push:
    paths: ["**.py", "pyproject.toml", ".ruff.toml"]
  pull_request:
    paths: ["**.py", "pyproject.toml", ".ruff.toml"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Black (check)
        run: black --check .
      - name: Ruff (lint)
        run: ruff check .
